### ISSUE TITLE
RSSから10分ごとに今週の週刊誌が流れてきます

### ISSUE THREAD

**Issue by ParkJong-Hun** [AndroidDagashi/AndroidDagashi#3147]
<img width="781" alt="スクリーンショット 2024-04-08 10 58 52" src="https://github.com/AndroidDagashi/AndroidDagashi/assets/81838716/f58fc3af-90cf-481f-8c1a-e8b6668f79a3">

昨日の午後9時26分から今日まで10分ごとにこのフィードが流れてます。
他に購読したRSSはこうならなく、AndroidDagashiのみこうなるので調査のほどよろしくお願いいたします。
（RSS購読をし直してもダメでした）

**Comment by yshrsmz** [comment]
Twitter で `slack rss` で検索してみたところ、AndroidDagashi に限らず、複数名が同じような不具合を報告していました。

https://twitter.com/search?q=slack%20rss&src=typed_query&f=live

おそらく Slack 側の不具合だと思われるので、我々の方でできることは特にないです 🙇

**Comment by ParkJong-Hun** [comment]
失礼しました。ありがとうございます。

**Comment by yshrsmz** [comment]
RSSフィード生成周りのロジックはここ数ヶ月いじってないので謎なんですよね
(ちなみに弊社だと AndroidDagashi のフィードは暴走してないようでした…)

**Comment by ParkJong-Hun** [comment]
私はAndroidDagashi（このレポジトリ）のロジックが変わってないから、内部的に何かサーバーがあってそこを変えたのか　Githubを用いたもののRSSが金曜のGithubが不安定でそれ以降影響が出たのかと予測しました。
Slackワークスペースごとに一部RSSに問題が出てるのであればそうでもなさそうですね...。

**Comment by ParkJong-Hun** [comment]
Slackの不具合らしいです。
