### ISSUE TITLE
Android アプリ の DI コンテナとして KOIN を使う理由とちょこっとした紹介

### ISSUE THREAD

**Issue by hkurokawa** [AndroidDagashi/AndroidDagashi#331]
BattleProgrammerShibata](https://bps-tomoya.hateblo.jp/entry/2018/07/21/142503

[Fragmented の ep. 133](http://fragmentedpodcast.com/episodes/133/)でも取り上げられて注目を浴びているKOINの紹介です

**Comment by hkurokawa** [comment]
ちょっとしたホビープロジェクトならこれで十分だと思いますが、自分は依存グラフの作成と解決がDIライブラリの一番の強みだと思っているので、大きなアプリでこれだと辛いかなぁ、と思いましたが、どうでしょうか。

**Comment by yshrsmz** [comment]
[実は先週取り上げてます](https://github.com/AndroidDagashi/AndroidDagashi/issues/320)

**Comment by yshrsmz** [comment]
Fragmentedのep紹介をメインにしたほうがいいかもです

**Comment by hkurokawa** [comment]
Oh... すみません、どこかで見たなと思っていましたが、Dagashi経由であることを忘れていました :bowing_man: :sweat_drops:  閉じますね :dogeza:

**Comment by hkurokawa** [comment]
Fragmented の方は聴き途中なので終わったら載せます :sweat_drops:
