### ISSUE TITLE
書籍「Clean Architecture」が最高すぎたのでエッセンスをまとめてみた

### ISSUE THREAD

**Issue by yshrsmz** [AndroidDagashi/AndroidDagashi#364]
https://qiita.com/tmknom/items/72eab3759ae523b526d1

Androidに限った話ではありませんが

**Comment by hkurokawa** [comment]
削除されているっぽい？

**Comment by yshrsmz** [comment]
おや。ありがとうございます。
引用の要件満たしてるの？　とか指摘されてたみたいですね
